Tejpal branch
Pawan1005/MI-14-MEAN pull request #12
Opened 2021-12-17 07:23 UTC by tejpalDarro

2021-12-24 07:02 UTC, Pawan1005 requested changes

2021-12-24 07:02 UTC, Pawan1005 commented on tejpalFolder/Assignment1/questions.txt
> +To install Git, run the following command: sudo apt-get install git-all.
remove -all from cmd

2021-12-24 07:02 UTC, Pawan1005 commented on tejpalFolder/Assignment1/questions.txt
> +You've configured Git with a global username/email address and an optional repository-specific username/email
add proper command for global user/name

2021-12-24 08:00 UTC, merged

2021-12-28 04:48 UTC, tejpalDarro commented on tejpalFolder/Assignment1/questions.txt
> +You've configured Git with a global username/email address and an optional repository-specific username/email
done.

2021-12-28 04:53 UTC, tejpalDarro commented on tejpalFolder/Assignment1/questions.txt
> +To install Git, run the following command: sudo apt-get install git-all.
done.