added balaji assignment
Pawan1005/MI-14-MEAN pull request #20
Opened 2021-12-28 10:19 UTC by jamge

2021-12-28 10:49 UTC, jarandeshubham approved these changes

2021-12-29 12:21 UTC, Pawan1005 requested changes

2021-12-29 12:21 UTC, Pawan1005 commented on balaji/html1.html
> +</html>
add new line at the end of file

2021-12-29 12:21 UTC, Pawan1005 commented on balaji/html2.html
> +
remove extra lines

2021-12-29 12:21 UTC, Pawan1005 commented on balaji/html2.html
> +</html>
add new line

2021-12-29 12:21 UTC, Pawan1005 commented on balaji/html3.html
> +
remove extra lines

2021-12-29 12:21 UTC, Pawan1005 commented on balaji/html3.html
> +    <title></title>
add title

2021-12-29 12:21 UTC, Pawan1005 commented on balaji/html3.html
> +</html>
add new line

2021-12-29 12:21 UTC, Pawan1005 commented on balaji/html4.html
> +</html>
add new line

2022-01-10 12:21 UTC, Pawan1005 approved these changes

2022-01-11 16:36 UTC, merged