added file htmlassign 2Kaveri@work
Pawan1005/MI-14-MEAN pull request #36
Opened 2021-12-29 16:04 UTC by kaverigond19945

2021-12-30 06:14 UTC, srigowrideo approved these changes

2021-12-31 07:02 UTC, Pawan1005 requested changes

2021-12-31 07:02 UTC, Pawan1005 commented on kaverigond/HTML/html assign/kaveri_assign/Q2.html
> +        </body>
html  tag closing missing

2021-12-31 07:02 UTC, Pawan1005 commented on kaverigond/HTML/html assign/kaveri_assign/Q4.html
> +    </head>
wrong code 
head tag need to close before body tag
html closing tag is also missing

2021-12-31 07:02 UTC, Pawan1005 commented on kaverigond/html assign 2/my 2ndhtml.html
> +    <body>The Google story begins in 1995 at <b> Stanford University.</b>
wrong body tag

2021-12-31 07:02 UTC, Pawan1005 commented on kaverigond/html assign 2/my 2ndhtml.html
> +     <body><i> This article is about the company. </i></body>
body tag needs to close at end of file before closing of html tag

2021-12-31 07:02 UTC, Pawan1005 commented on kaverigond/html assign 2/my 2ndhtml.html
> +        </body>
remove this body tag you can have only one body tag in code

2021-12-31 07:02 UTC, Pawan1005 commented on kaverigond/html assign 2/my 2ndhtml.html
> +    </html>
add new line at the end of file

2022-01-06 06:07 UTC, anitawankhade1994 approved these changes

2022-01-07 14:54 UTC, srigowrideo approved these changes

2022-01-10 12:21 UTC, Pawan1005 approved these changes

2022-01-11 09:58 UTC, srigowrideo approved these changes

2022-01-11 16:37 UTC, merged